services:

  # ==============================
  # OpenSearch
  # ==============================
  opensearch:
    build:
      context: ./docker/opensearch
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=${OPENSEARCH_JAVA_OPTS}
      - bootstrap.memory_lock=true
      - DISABLE_SECURITY_PLUGIN=${DISABLE_SECURITY_PLUGIN}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "${OPENSEARCH_PORT}:9200"
      - "9600:9600"
    networks:
      - jewellery-network

  # ==============================
  # FastAPI Search API
  # ==============================
  api:
    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile
    container_name: jewellery-search-api
    restart: always
    env_file:
      - .env
    ports:
      - "${API_PORT}:8000"
    volumes:
      - .:/app
    depends_on:
      - opensearch
    networks:
      - jewellery-network


# ==============================
# Volumes
# ==============================
volumes:
  opensearch-data:

# ==============================
# Networks
# ==============================
networks:
  jewellery-network:
    driver: bridge
